### ISSUE TITLE
Firebase structure images

### ISSUE THREAD

**Issue by Techxjunkie** [melmatx/QuickCart#1]
Hello, could you please provide images for the firebase store setup for product list and categories?  I keep getting error Type null is not a subtype of String.  I know it's because my setup is wrong.  Could you provide this please?  Thanks

**Comment by melmatx** [comment]
### Sample Category 1: Mobile

| Field | Type | Value |
|--------|--------|--------|
| id          | string  | QAhvxP54A20HIgUuTQOo |
| image  | string   | https://smart.com.ph/Postpaid/images/default-source/iphone14/pro-max/ip14-pro-white.png |
| name   | string   | Mobile | 

- To insert products on this category, make a collection inside it named **products**, then start adding products on that collection:
<img width="886" alt="image" src="https://github.com/melmatx/QuickCart/assets/87235413/7a6ed1a0-f604-4152-badb-a9a51a03052d">


### Sample Product 1: 
| Field | Type | Value |
|--------|--------|--------|
| id          | string  | Tescp0La1iiKLdUIqh0K |
| image  | string   | https://www.ft.com/__origami/service/image/v2/images/raw/https%3A%2F%2Fd1e00ek4ebabms.cloudfront.net%2Fproduction%2F217430e4-7b71-4e37-b1aa-34f288123cc5.png?fit=scale-down&source=next&width=700 |
| name   | string   | iPhone 14 Pro Max | 
| price    | number | 1200 |
| description | string | The iPhone 14 Pro Max is one of the most durable, speedy, and powerful devices. Enjoy high-speed reactivity thanks to the new A16 Bionic chip, the best battery yet, and a new customizable lock screen that fits your needs. The iPhone 14 Pro Max contains new features, such as the Dynamic Island, that keeps music, FaceTime, and more at your fingertips, along with a 65% larger sensor and 4x the resolution that helps you capture more detail than ever before. Let’s not forget that the iPhone 14 Pro Max brings 2x brighter lighting and all-day battery life to this device. And let’s not forget the iPhone 14 Pro Max’s newest live-saving technology: Collision Detection and Emergency SOS. |

**Comment by Techxjunkie** [comment]
Awesome, thanks!
